"""initial_schema

Revision ID: 8678818e71a3
Revises: 
Create Date: 2025-11-29 13:31:22.836301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8678818e71a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique knowledge chunk identifier (UUID)'),
    sa.Column('source', sa.String(length=255), nullable=False, comment="Source of the chunk (e.g., 'enhanced_readme', 'docs', module name)"),
    sa.Column('external_id', sa.String(length=500), nullable=True, comment='External identifier (e.g., file path + chunk index, section ID)'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Chunk title or heading'),
    sa.Column('content', sa.Text(), nullable=False, comment='Chunk content/text'),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True, comment='Additional metadata (section_type, module, line_numbers, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_created', 'knowledge_chunks', ['created_at'], unique=False)
    op.create_index('idx_knowledge_external_id', 'knowledge_chunks', ['external_id'], unique=False)
    op.create_index('idx_knowledge_source', 'knowledge_chunks', ['source'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_external_id'), 'knowledge_chunks', ['external_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_source'), 'knowledge_chunks', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier (UUID)'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='External user ID from authentication system (optional)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment="User's display name"),
    sa.Column('email', sa.String(length=255), nullable=True, comment="User's email address (unique, nullable for guest users)"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique conversation identifier (UUID)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who owns this conversation (nullable for anonymous)'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Conversation title (auto-generated or user-provided)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="Conversation status: 'active' or 'archived'"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_created', 'conversations', ['created_at'], unique=False)
    op.create_index('idx_conversation_user_status', 'conversations', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique message identifier (UUID)'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Conversation this message belongs to'),
    sa.Column('sender_type', sa.String(length=50), nullable=False, comment="Type of sender: 'user', 'assistant', or 'system'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content/text'),
    sa.Column('role_metadata', sa.JSON(), nullable=True, comment='Additional metadata (tool calls, retrieved chunks, token counts, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_message_sender_type', 'messages', ['sender_type'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_type'), 'messages', ['sender_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_message_sender_type', table_name='messages')
    op.drop_index('idx_message_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index('idx_conversation_user_status', table_name='conversations')
    op.drop_index('idx_conversation_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_chunks_source'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_external_id'), table_name='knowledge_chunks')
    op.drop_index('idx_knowledge_source', table_name='knowledge_chunks')
    op.drop_index('idx_knowledge_external_id', table_name='knowledge_chunks')
    op.drop_index('idx_knowledge_created', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###

